
<footer class="footer container-fluid mt-5">
	<div class="justify-content-center row ">
		<ul class="">
			<li class="list-inline-item"><p class="text-center text-muted">&copy; 2016 All rights reserved</p></li>
			<li class="list-inline-item">
				<a href="/about">About Us</a>
			</li>
			<li class="list-inline-item">
				<a href="/privacy">Privacy Policy</a>
			</li>
			<li class="list-inline-item">
				<a href="/terms">Terms And Conditions</a>
			</li>
			<li class="list-inline-item">
				<a href="/disclaimer">Disclaimer</a>
			</li>
			<li class="list-inline-item">
				<a href="/contact">Contact Us</a>
			</li>
		</ul>

	</div>
</footer>

<button onclick="$(this).hide(); window.scroll({ top: 0, left: 0, behavior: 'smooth' });" id="gotop" title="Go to top" ><b>&nbsp;&Delta;&nbsp;</b></button>
<style>
#gotop {
display: none;
position: fixed;
bottom: 20px;
right: 30px;
z-index: 99;
border: none;
outline: none;
background-color: orange;
color:#333;
cursor: pointer;
padding: 11px  12px;
border-radius: 30px;
}
</style>
<script>
$(document).ready(function(){
	var p = 1*$('.footer.container-fluid').offset().top
	var s = 1*$('.footer.container-fluid').height()
	var h = 1*$(window).height();
	if(p+s+30 < h){
		$('.footer.container-fluid').css({"padding-top":h-s-p-20})
	}


        $( window ).scroll(function() {
		//_d(document.body.scrollTop);
		//_d(document.documentElement.scrollTop);
            if (document.body.scrollTop > 120 || document.documentElement.scrollTop > 120) {
		   $("#gotop").show();
            } else {
		  $("#gotop").hide();
            }
    	});

})
</script>

<style>
html { height:101%;}
</style>

</body>
</html>
