
<br><br>
<div class="row justify-content-center">
<div class="modal-content col-6">
                <div class="modal-header  login-logo">
                        <h3 class="">Alarm</h3>
                </div>
                <div class="modal-body text-center">
                        <div id="timer" class="row">
                                <div class="col-md-6">
                                        <h2>TIME LEFT</h> 
                                </div>

                                <div class="col-md-6">
                                        <h2>DIGITAL CLOCK</h> 
                                </div>

                                <div class="col-md-6">
                                        <h2 id="left">00:00:00</h> 
                                </div>
                                <div class="col-md-6">
                                        <h2 id="clock">00:00:00</h> 
                                </div>                                
                                <div class="col-md-12">
                                &nbsp;
                                </div>
                                <div class="col-md-6">
                                <h2><i class="fa fa-chevron-up hand"  onclick="h_add(1)"  aria-hidden="true"></i>&nbsp;&nbsp;<i class="fa fa-chevron-up hand"  onclick="m_add(1)"  aria-hidden="true"></i>&nbsp;&nbsp;<i class="fa fa-chevron-up" onclick="s_add(1)" aria-hidden="true"></i></h2> 
                                <h2 id="display">00:00:00</h> 
                                <h2><i class="fa fa-chevron-down hand"  onclick="h_add(-1)"  aria-hidden="true"></i>&nbsp;&nbsp;<i class="fa fa-chevron-down"  onclick="m_add(-1)" aria-hidden="true"></i>&nbsp;&nbsp;<i class="fa fa-chevron-down"  onclick="s_add(-1)"  aria-hidden="true"></i></h2> 
                                </div>
                                <div class="col-md-6">
                                <h2><label><input type="checkbox" id="tick" value="1" onclick="change_tick()"> &nbsp;Ticking sound</label></h2>
                                <h2><i class="fa fa-stop" onclick="stop()" aria-hidden="true"></i>&nbsp;&nbsp;<i class="fa fa-play" onclick="go()" aria-hidden="true"></i></i></h2> 
                                <h2>&nbsp;</h2>
                                </div>
                        </div>                
                </div>
                <div class="modal-body text-center">
                                <button type="button" class="btn btn-lg btn-warning" onclick="done()" id="save">
                                        <span>DONE</span>
                                </button>
                </div>
        </div>
</div>

<script>
var _seconds;
var _minutes;
var _hours;

var h=0;
var m=0;
var s=0;
var on=false;
var ticked=false;
var _done=false;
var ls=0;
common.sound._vol = 200
$('#save').hide()

function change_tick(){ ticked = $('#tick').is(':checked') }

function h_add(i){
        if(ticked) common.sound.keyin()
        h = h+i;
        if(h < 0) h=23;
        if(h > 23) h=0;
        paint();
}
function m_add(i){
        if(ticked) common.sound.keyin()
        m = m+i;
        if(m < 0) m=59;
        if(m > 59) m=0;
        paint();
}
function s_add(i){
        if(ticked) common.sound.keyin()
        s = s+i;
        if(s < 0) s=59;
        if(s > 59) s=0;
        paint();
}

function s_sub(){
        if($('#clock').html() == $('#display').html()){
                stop();
                $('#save').show();
                return finished()   
        }
        return false;
}

function paint(){
        var a='';
        a += h > 9 ? h: "0"+h;
        a +=":";
        a += m > 9 ? m: "0"+m;
        a +=":";
        a += s > 9 ? s: "0"+s;
        $('#display').html(a);
}

function go(){
        if(!h && !s && !m) return;
        $('.fa-stop, .fa-pause').addClass('_Red');
        on = true
}


function stop(){
        h=m=s=0;
        on = false;
        $('#left').html("00:00:00")
        $('.fa-stop, .fa-pause').removeClass('_Red');
        paint();
}

function finished(){
        common.sound.ok();
        $( "body" ).effect( "highlight");
        setTimeout(function(){ if(!_done){ $('title').html(++ls %2 ? 'Alarm':'ALARM'); finished()}else{ $('#save').hide();  $('title').html('TIMER')}; }, ls %2 ? 250:850  ) 
}

function done(){
        $('#left').html("00:00:00")
        _done = true;

}

$(document).ready(function() {
// Create two variable with the names of the months and days in an array
//         var monthNames = [ "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" ];
//         var dayNames= ["Sun","Mon","Tue","Wed","Thu","Fri","Sat"]

// // Create a newDate() object
//         var newDate = new Date();
// // Extract the current date from Date object
//         newDate.setDate(newDate.getDate());
// // Output the day, date, month and year
//         $('#_date').html(  monthNames[newDate.getMonth()]+ " " + newDate.getDate() + ' ' +dayNames[newDate.getDay()] );

        setInterval( function() {
            // Create a newDate() object and extract the seconds of the current time on the visitor's
            _seconds = new Date().getSeconds();
            // Create a newDate() object and extract the minutes of the current time on the visitor's
            _minutes = new Date().getMinutes();
            // Create a newDate() object and extract the hours of the current time on the visitor's
            _hours = new Date().getHours();

            var t =     ( _hours < 10 ? "0" : "" ) + _hours + ":" + (_minutes < 10 ? "0" : "" ) + _minutes + ":" + ( _seconds < 10 ? "0" : "" ) + _seconds

            $('#clock').html(t);





                if(!on) return;
                if(ticked) common.sound.keyin()
                s_sub();



                var delta = h*60*60 + m*60 + s -_hours*60*60 - _minutes*60 - _seconds
                if(delta <0) delta += 24 * 60 * 60;
                var _h = Math.floor(delta / (60*60) ) 
                var _m = Math.floor((delta - _h*60*60) / 60)
                var _s = (delta - _h*60*60 - _m*60)

                var t =     ( _h < 10 ? "0" : "" ) + _h + ":" + (_m < 10 ? "0" : "" ) + _m + ":" + ( _s < 10 ? "0" : "" ) + _s
                $('#left').html(t);

        }, 1000);
    });

</script>

<style>
#timer{
font-family:"Lucida Console", Monaco, monospace;
}
#timer h2{
padding:0;
margin:0;
background:#000;
color:#fff;
font-weight: 900;
}
</style>