<?php

//system:
$_SYSTEM = [
	'DIRECTORY_SEPARATOR'=>DIRECTORY_SEPARATOR,
	'PHP_SHLIB_SUFFIX'=>PHP_SHLIB_SUFFIX,
	'PATH_SEPARATOR'=>PATH_SEPARATOR,
	'PHP_OS'=>PHP_OS,
	'uname'=>php_uname(),
	'phpversion'=>phpversion(),
	'php_sapi_name'=>php_sapi_name(),
	'current_user'=>get_current_user(),
	'temp_dir'=>sys_get_temp_dir(),
];
$_MODULE = get_loaded_extensions();
?>

<div class="container-fluid" id="sixthTable">
	<!-- The Modal -->

	<div class="container">
		<h3 class="text-uppercase mt-5">System Parameters</h3>
		<ul class="nav nav-tabs">
	          <li><a data-toggle="tab" class="start-here" href="#menu1">Defined Constants</a></li>
	          <li><a data-toggle="tab" href="#menu2">$ SERVER VARS</a></li>
	          <li><a data-toggle="tab" href="#menu3">$ ENV VARS</a></li>
		  <li><a data-toggle="tab" href="#menu4">$ SYSTAM</a></li>
		  <li><a data-toggle="tab" href="#menu5">Extensions</a></li>
	        </ul>

	        <div class="tab-content">
	          <div id="menu1" class="tab-pane fade">
			    <table class="table table-striped table-hover">
				  <tr>
					  <th>Name</th>
					  <th>Value</th>
				  </tr>
				  <?php foreach($rs['constants'] as $k=>$v):?>
				  <tr>
					  <td><?=$k;?></td>
					  <td><?=$v;?></td>
				  </tr>
				  <?php endforeach;?>
			  </table>
	          </div>
	          <div id="menu2" class="tab-pane fade">
			  <table class="table table-striped table-hover">
				<tr>
					<th>Name</th>
					<th>Value</th>
				</tr>
				<?php foreach($_SERVER as $k=>$v):?>
				<tr>
					<td>$_SERVER[<b>'<?=$k;?>'</b>]</td>
					<td><?=$v;?></td>
				</tr>
				<?php endforeach;?>
			</table>
	          </div>
	          <div id="menu3" class="tab-pane fade">
			  <table class="table table-striped table-hover">
				<tr>
					<th>Name</th>
					<th>Value</th>
				</tr>
				<?php foreach(getenv()  as $k=>$v):?>
				<tr>
					<td><?=$k;?></td>
					<td><?=$v;?></td>
				</tr>
				<?php endforeach;?>
			</table>
	          </div>

		  <div id="menu4" class="tab-pane fade">
			  <table class="table table-striped table-hover">
				<tr>
					<th>Name</th>
					<th>Value</th>
				</tr>
				<?php foreach($_SYSTEM  as $k=>$v):?>
				<tr>
					<td><?=$k;?></td>
					<td><?=$v;?></td>
				</tr>
				<?php endforeach;?>
			</table>
	          </div>
		  <div id="menu5" class="tab-pane fade">
			  <table class="table table-striped table-hover">
				<tr>
					<th>Name</th>
					<th>Value</th>
				</tr>
				<?php foreach($_MODULE  as $k=>$v):?>
				<tr>
					<td><?=$k;?></td>
					<td><?=$v;?></td>
				</tr>
				<?php endforeach;?>
			</table>
	          </div>

	        </div>

	</div>

</div>
<hr>
<script>
(function(){

setTimeout(function(){ $('.start-here').click()}, 400);

})()
</script>
<style>
ul.nav{
	width:100%;

}
ul.nav > li {
	margin-bottom:25px;
}
ul.nav > li > a{
	padding:10px 30px 4px 20px;
	margin-bottom:5px;
	border-bottom: 1px solid #ddd;
	border-left: 0px solid #ddd;
	border-right: 0px solid #ddd;
	border-top: 0px solid #ddd;
}
ul.nav > li a.active{
	border-bottom: 0px solid #ddd;
	border-left: 1px solid #ddd;
	border-right: 1px solid #ddd;
	border-top: 1px solid #ddd;
	color:Olive;
	font-style: italic;
}
</style>
