<?php


?>


<?php include _X_LAYOUT . '/sitemin/include_vue.phtml'; ?>

<script>
var _token='<?=$rs['_token'];?>';
</script>
<div class="container-fluid" id="sixthTable">
	<div class="row">
		<div class="col-md-12">
			<h3 class="text-uppercase mt-5">PHP Code Beautfy</h3>
			<br>
			<!-- file permission-->
			<div class="form-group file-permission">
				<div class="alert alert-info">Follow permission required</div>
				<!-- file permission-->
				<div class="permission"> </div>
				<div class="clear"></div>
				<!-- retry -->
				<span class="floatRight re-test-file"> Please change the permission  by "chmod", "chown", and  <button type="button" id="re-test-file" class="none btn btn-danger " onclick="test_file_permission()"> Test again</button></span>
				<br/>
				<script>
					(function($){
						test_file_permission()
					})(jQuery)
					function test_file_permission(){
						$('.permission').html("");
						common.mask.up();
						$.ajax({
							dataType:'json',
							data:{cmd:'file permission', _token:'<?=$rs['_token'];?>', a:Math.random()},
							type:'post',
							success: function(ret){
								if(ret.data.failed)
								ret.data.failed.forEach(function(v, i){
										$('.permission').append('<div class="alert alert-warning wp100"><strong><i class="fa fa-window-close" aria-hidden="true"></i></strong> ' + v + ' <span class="badge badge-warning">Check\'s failed</span></div>')
									})
								if(ret.status != 'failed'){
									$('.action-table').show();
									$('.file-permission').hide();
								}
								common.mask.down();
							}
						});
					}
				</script>
			</div>
			<div class="clear"></div>
		
		</div>	
			
		<div class="col-md-5 action-table Hide">
			<div class="CODE status"></div>
		</div>
		<div class="col-md-6 left-panel  action-table Hide">
			<?php if(!$rs['beautifier']):?>
				<div class="alert alert-warning">
				<strong>Missing command line "PHP_Beautifier"!</strong> run "pear install PHP_Beautifier" ,  click <a href="https://pear.php.net/package/PHP_Beautifier" target="_blank" class="alert-link">here</a> for more info.
				</div>
			<?php else:?>
				<div>
					<button type="button" class="btn btn-primary" onclick="beautify()">Apply Now</button>
				</div>
			<?php endif;?>
			<p><?=$rs['tree'];?></p>

		</div>
	</div>

</div>
<script>
var aa=0;
(function(){
	//apply to php only
	$('.xp-tree-file .name').each(function(){
		var name = $(this).html();
		if(!name.match(/\.php$/ig))
			$(this).parent().parent().parent().remove();
		$(this).attr('data-path', name).html(name.replace(/\s+[\/].*[\/]/ig, ''))
		$(this).prev().val(name)

	})
	$('#sixthTable ul').each(function(){
		if($(this).find('.xp-tree-file').length==0)
			$(this).remove();
	})
	$('#sixthTable li.xp-tree-dir').each(function(){
		if($(this).next().find('.xp-tree-file').length==0)
			$(this).remove();
			//console.log($(this).css({border:"3px red solid"}));
	})


	$('.status').parent().height( Math.max(1000, $('.left-panel').height())).css({background:'#eee'});


})()



function beautify(){
	if(!$('#sixthTable input:checked').length){
		return common.mask.down();
	}

	var e = $('#sixthTable input:checked')[0];
	$(e).prop( "checked", false );
	if($(e).hasClass('final')){
		var file = $(e).val().replace(/^\s+\d+\s+.*?\s+/g,'');
		common.mask.down();
		common.mask.up();
		$.ajax({
			url: "<?=_r_url();?>/?cmd=apply&v="+file,
			//dataType: 'json',
			//data: $(e.form).serialize(),
			success: function(data) {
				$('.status').append("<p >"+data.replace('<?=_X_ROOT;?>', '')+"</p>");
				setTimeout(function(){ beautify(); }, 1);
				var t = $('.status').offset().top
				var h = $('.status').height()
				var wh = $(window).height();
				if((h+t) > wh) window.scrollTo(0, h-t);

			}
		});
	}else{
		setTimeout(function(){ beautify(); }, 1);
	}
}
</script>
<hr>
