<?php


?>


<?php include _X_LAYOUT . '/sitemin/include_vue.phtml'; ?>

<script>
var _token='<?=$rs['_token'];?>';
</script>
<div class="container-fluid" id="sixthTable">
	<div class="row">
		<div class="col-md-3">
		</div>
		<div class="col-md-6">
			<h3 class="text-uppercase mt-5">Install Zipped Module</h3>

		<!-- file permission-->
		<div class="form-group file-permission">
			<div class="alert alert-info">Follow permission required</div>
			<!-- file permission-->
			<div class="permission"> </div>
			<div class="clear"></div>
			<!-- retry -->
			<span class="floatRight re-test-file"> Please change the permission  by "chmod", "chown", and  <button type="button" id="re-test-file" class="none btn btn-danger " onclick="test_file_permission()"> Test again</button></span>
			<br/>
			<script>
				(function($){
					test_file_permission()
				})(jQuery)
				function test_file_permission(){
					$('.permission').html("");
					common.mask.up();
					$.ajax({
						dataType:'json',
						data:{cmd:'file permission', _token:'<?=$rs['_token'];?>', a:Math.random()},
						type:'post',
						success: function(ret){
							if(ret.data.ok)
							ret.data.ok.forEach(function(v, i){
									$('.permission').append('<div class="alert alert-success wp100"><strong><i class="fa fa-check-square" aria-hidden="true"></i></strong> ' + v + ' <span class="badge badge-success">Check\'s OK</span></div>')
								})
							if(ret.data.failed)
							ret.data.failed.forEach(function(v, i){
									$('.permission').append('<div class="alert alert-warning wp100"><strong><i class="fa fa-window-close" aria-hidden="true"></i></strong> ' + v + ' <span class="badge badge-warning">Check\'s failed</span></div>')
								})
							if(ret.status != 'failed'){
								$('.left-panel').show();
								$('.re-test-file').hide();
							}
							common.mask.down();
						}
					});
				}
			</script>
		</div>
		<div class="clear"></div>


		</div>
		<div class="col-md-3">
		</div>

		<div class="col-md-3">
		</div>
		<div class="col-md-6 left-panel Hide">
			<p> If this is new installed project:<p>
			<p>There is "c.zip" file for testinstallation, under your [PROJECT FOLDER]/code/data/system/ <p>
				<hr>
			<h1> </h1>			
			<?php if($rs['msg']):?>
			<div class="jumbotron">
			  <h1>File Received</h1>
			  <?php foreach($rs['msg'] as $k=>$v):?>
				  <p><?php
				  	switch(true){
						case preg_match('/^\*/ims', $v):
							echo "<span class='alert alert-warning'>$v</span>";
							break;
						case preg_match('/^\-\-\-/ims', $v):
							echo "<hr>";
							break;
						case preg_match('/^\-\s/ims', $v):
							echo "<b>$v</b>";
							break;
						default:
							echo "<span>$v</span>";
							break;
					}
				  ?></p>
			  <?php endforeach;?>
			</div>
			<?php endif;?>

			<?php if(!$rs['unzip']):?>
				<div class="alert alert-warning">
				<strong>Missing command line "UNZIP"!</strong> please install command line 'UNZIP'.
				</div>
			<?php else:?>
			<form method="post" enctype="multipart/form-data">
				<input type="hidden" name='_token' value="<?=$rs['_token'];?>"/>
				<div class="form-group">
					<label for="email">Select zip file to upload:</label>
					<input type="file" name="name" id="name" class="form-control-file border" required/>
					<button type="submit" class="btn btn-primary">Upload Now</button>
				</div>
			</form>
			<?php endif;?>
			<p><?=$rs['tree'];?></p>

		</div>
	</div>

</div>
<?php //_d($rs['msg']);?>
<script>
(function(){


})()

</script>
<hr>
