<?php


$apache_data=
array (
  'REDIRECT_STATUS' => '200',
  'HTTP_HOST' => 'localhost',
  'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:75.0) Gecko/20100101 Firefox/75.0',
  'HTTP_ACCEPT' => 'application/json, text/javascript, */*; q=0.01',
  'HTTP_ACCEPT_LANGUAGE' => 'en-US,en;q=0.5',
  'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
  'CONTENT_TYPE' => 'application/x-www-form-urlencoded; charset=UTF-8',
  'HTTP_X_REQUESTED_WITH' => 'XMLHttpRequest',
  'CONTENT_LENGTH' => '120',
  'HTTP_ORIGIN' => 'http://localhost',
  'HTTP_CONNECTION' => 'keep-alive',
  'HTTP_REFERER' => 'http://localhost/aws/cs/MyProject/sitemin/install',
  'PATH' => 'C:\\Python38\\Scripts\\;C:\\Python38\\;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\iCLS\\;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\iCLS\\;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files\\Intel\\WiFi\\bin\\;C:\\Program Files\\Common Files\\Intel\\WirelessCommon\\;C:\\Users\\pwang.HFM\\WinSCPInstall\\;C:\\Users\\pwang.HFM\\GitInstall\\cmd;C:\\Program Files\\Git\\cmd;C:\\Program Files (x86)\\Microsoft SQL Server\\Client SDK\\ODBC\\130\\Tools\\Binn\\;C:\\Program Files (x86)\\Microsoft SQL Server\\140\\Tools\\Binn\\;C:\\Program Files (x86)\\Microsoft SQL Server\\140\\DTS\\Binn\\;C:\\Program Files (x86)\\Microsoft SQL Server\\140\\Tools\\Binn\\ManagementStudio\\;C:\\Program Files\\nodejs\\;C:\\ProgramData\\chocolatey\\bin;C:\\Users\\pwang.HFM\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\pwang.HFM\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Users\\pwang.HFM\\AppData\\Local\\atom\\bin;C:\\Program Files\\Java\\jdk-11.0.6\\bin;C:\\Users\\pwang.HFM\\Downloads\\nssm-2.24\\win64;C:\\Users\\pwang.HFM\\AppData\\Roaming\\npm',
  'SystemRoot' => 'C:\\WINDOWS',
  'COMSPEC' => 'C:\\WINDOWS\\system32\\cmd.exe',
  'PATHEXT' => '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW',
  'WINDIR' => 'C:\\WINDOWS',
  'SERVER_SIGNATURE' => '<address>Apache/2.4.37 (Win32) PHP/5.6.40 Server at localhost Port 80</address>
',
  'SERVER_SOFTWARE' => 'Apache/2.4.37 (Win32) PHP/5.6.40',
  'SERVER_NAME' => 'localhost',
  'SERVER_ADDR' => '::1',
  'SERVER_PORT' => '80',
  'REMOTE_ADDR' => '::1',
  'DOCUMENT_ROOT' => 'C:/wamp/www',
  'REQUEST_SCHEME' => 'http',
  'CONTEXT_PREFIX' => '',
  'CONTEXT_DOCUMENT_ROOT' => 'C:/wamp/www',
  'SERVER_ADMIN' => 'wampserver@wampserver.invalid',
  'SCRIPT_FILENAME' => 'C:/wamp/www/aws/cs/MyProject/index.php',
  'REMOTE_PORT' => '64272',
  'REDIRECT_URL' => '/aws/cs/MyProject/sitemin/install',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'REQUEST_METHOD' => 'POST',
  'QUERY_STRING' => '',
  'REQUEST_URI' => '/aws/cs/MyProject/sitemin/install',
  'SCRIPT_NAME' => '/aws/cs/MyProject/index.php',
  'PHP_SELF' => '/aws/cs/MyProject/index.php',
  'REQUEST_TIME_FLOAT' => 1586678245.1570001,
  'REQUEST_TIME' => 1586678245,
  'X2CLI_CALL' => true,
)
define('__X_DEBUG', true);

